import { loadEnv } from "./env";

loadEnv();

/** Build a tiny, valid one-page PDF so demo "View"/"Download" actually work. */
function placeholderPdf(title: string, subtitle: string): Buffer {
  const esc = (s: string) => s.replace(/[\\()]/g, "\\$&").slice(0, 70);
  const content = `BT /F1 20 Tf 60 720 Td (${esc(title)}) Tj ET
BT /F1 11 Tf 60 694 Td (${esc(subtitle)}) Tj ET
BT /F1 10 Tf 60 660 Td (Demo placeholder generated by the StudyHub seed script.) Tj ET
BT /F1 10 Tf 60 644 Td (Replace it with your own material from the admin dashboard.) Tj ET`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) pdf += `${String(off).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "latin1");
}

type SeedMaterial = {
  title: string;
  description: string;
  category: string;
  instructor?: string;
  tags: string[];
  status?: "draft" | "published";
  /** Lawful, publicly available reference instead of a copied file. */
  externalUrl?: string;
  daysAgo: number;
  downloads?: number;
};

type SeedSubject = { name: string; code: string; icon: string; materials: SeedMaterial[] };
type SeedSemester = { name: string; short: string; description: string; subjects: SeedSubject[] };

const CATEGORIES = [
  { name: "Lecture Notes", icon: "notebook", description: "Slides and notes from class." },
  { name: "Text Books", icon: "book-open", description: "Reference books and reading lists." },
  { name: "Assignments", icon: "clipboard-list", description: "Handouts, tasks and submissions." },
  { name: "Past Papers", icon: "file-clock", description: "Previous midterms and finals." },
  { name: "Presentations", icon: "presentation", description: "Student and lecturer decks." },
  { name: "External Resources", icon: "link", description: "Links to course sites and videos." },
];

const DATA: SeedSemester[] = [
  {
    name: "Fifth Semester",
    short: "05",
    description: "Core computing foundations.",
    subjects: [
      {
        name: "Operating Systems",
        code: "CS-305",
        icon: "cpu",
        materials: [
          { title: "Processes and Threads — Lecture 03", description: "Process lifecycle, context switching and thread models with worked examples.", category: "Lecture Notes", instructor: "Dr. Hina Riaz", tags: ["processes", "threads", "scheduling"], daysAgo: 21, downloads: 64 },
          { title: "CPU Scheduling Problem Set 02", description: "FCFS, SJF and round-robin scheduling problems with a Gantt-chart worksheet.", category: "Assignments", tags: ["scheduling", "practice"], daysAgo: 12, downloads: 38 },
          { title: "Midterm 2024 — Operating Systems", description: "Last year's midterm paper, shared for practice.", category: "Past Papers", tags: ["midterm", "2024"], daysAgo: 30, downloads: 91 },
          { title: "Operating Systems — MIT 6.1810 course site", description: "Open courseware covering xv6, virtual memory and file systems.", category: "External Resources", tags: ["ocw", "xv6"], externalUrl: "https://pdos.csail.mit.edu/6.1810/", daysAgo: 9, downloads: 17 },
        ],
      },
      {
        name: "Database Systems",
        code: "CS-311",
        icon: "database",
        materials: [
          { title: "Normalization up to BCNF — Lecture 08", description: "Functional dependencies, 1NF through BCNF, and a decomposition walkthrough.", category: "Lecture Notes", instructor: "Dr. Hina Riaz", tags: ["normalization", "bcnf"], daysAgo: 4, downloads: 77 },
          { title: "SQL Joins Practice Assignment", description: "Twelve query exercises over a small university schema.", category: "Assignments", tags: ["sql", "joins"], daysAgo: 6, downloads: 52 },
          { title: "Transactions and Concurrency Deck", description: "ACID properties, isolation levels and two-phase locking.", category: "Presentations", tags: ["acid", "locking"], daysAgo: 15, downloads: 29 },
        ],
      },
      {
        name: "Computer Networks",
        code: "CS-321",
        icon: "network",
        materials: [
          { title: "Network Routing Notes — Lecture 06", description: "Distance-vector and link-state routing with a Dijkstra trace.", category: "Lecture Notes", tags: ["routing", "dijkstra"], daysAgo: 8, downloads: 45 },
          { title: "Subnetting Worksheet", description: "CIDR practice questions with an answer key on the last page.", category: "Assignments", tags: ["subnetting", "cidr"], daysAgo: 18, downloads: 33 },
          { title: "RFC 791 — Internet Protocol", description: "The original IPv4 specification from the IETF.", category: "External Resources", tags: ["rfc", "ipv4"], externalUrl: "https://www.rfc-editor.org/rfc/rfc791", daysAgo: 25, downloads: 8 },
        ],
      },
    ],
  },
  {
    name: "Sixth Semester",
    short: "06",
    description: "Systems, data and design.",
    subjects: [
      {
        name: "Software Engineering",
        code: "SE-301",
        icon: "settings",
        materials: [
          { title: "Requirements Engineering — Lecture 02", description: "Elicitation techniques, use cases and writing testable requirements.", category: "Lecture Notes", instructor: "Ms. Ayesha Khan", tags: ["requirements", "use-cases"], daysAgo: 3, downloads: 88 },
          { title: "SRS Document Template", description: "IEEE-style software requirements template for the semester project.", category: "Assignments", tags: ["srs", "template"], daysAgo: 11, downloads: 120 },
          { title: "Design Patterns Overview Deck", description: "Creational, structural and behavioural patterns with short code sketches.", category: "Presentations", tags: ["patterns", "design"], daysAgo: 19, downloads: 41 },
          { title: "Final Exam 2023 — Software Engineering", description: "Previous final paper for revision.", category: "Past Papers", tags: ["final", "2023"], daysAgo: 40, downloads: 63 },
        ],
      },
      {
        name: "Theory of Automata",
        code: "CS-302",
        icon: "sigma",
        materials: [
          { title: "Regular Languages and DFA Minimisation", description: "Closure properties, the pumping lemma and Hopcroft's minimisation.", category: "Lecture Notes", tags: ["dfa", "regular"], daysAgo: 14, downloads: 36 },
          { title: "Automata Practice Problems 03", description: "Construction exercises for NFA to DFA conversion.", category: "Assignments", tags: ["nfa", "practice"], daysAgo: 22, downloads: 27 },
        ],
      },
      {
        name: "Web Engineering",
        code: "SE-312",
        icon: "globe",
        materials: [
          { title: "HTTP and REST Fundamentals", description: "Request lifecycle, status codes, caching headers and REST constraints.", category: "Lecture Notes", tags: ["http", "rest"], daysAgo: 7, downloads: 55 },
          { title: "Semester Project Brief", description: "Scope, milestones and grading rubric for the group project.", category: "Assignments", tags: ["project"], daysAgo: 2, downloads: 94 },
          { title: "MDN Web Docs — Accessibility guide", description: "Reference material for the accessibility unit.", category: "External Resources", tags: ["a11y", "mdn"], externalUrl: "https://developer.mozilla.org/en-US/docs/Web/Accessibility", daysAgo: 16, downloads: 12 },
        ],
      },
    ],
  },
  {
    name: "Seventh Semester",
    short: "07",
    description: "Specialisation and the final-year project.",
    subjects: [
      {
        name: "Information Security",
        code: "CS-401",
        icon: "shield",
        materials: [
          { title: "Network Security — Lecture 07", description: "Threat models, defence in depth, firewalls and intrusion detection.", category: "Lecture Notes", instructor: "Dr. Usman Tariq", tags: ["network", "threat-model", "firewall"], daysAgo: 0, downloads: 143 },
          { title: "RSA and Public-Key Cryptography", description: "Key generation, modular exponentiation and a worked RSA example.", category: "Lecture Notes", instructor: "Dr. Usman Tariq", tags: ["rsa", "cryptography", "public-key"], daysAgo: 5, downloads: 118 },
          { title: "Security Assignment 02 — Hashing", description: "Compare hash functions and reason about collision resistance.", category: "Assignments", tags: ["hashing", "sha"], daysAgo: 1, downloads: 71 },
          { title: "Midterm 2025 — Information Security", description: "Most recent midterm paper.", category: "Past Papers", tags: ["midterm", "2025"], daysAgo: 20, downloads: 102 },
          { title: "NIST SP 800-63B — Digital Identity Guidelines", description: "Authoritative guidance on authentication and password policy.", category: "External Resources", tags: ["nist", "authentication"], externalUrl: "https://pages.nist.gov/800-63-3/sp800-63b.html", daysAgo: 13, downloads: 19 },
          { title: "Applied Cryptography reading list", description: "Recommended chapters and open-access papers for the crypto unit.", category: "Text Books", tags: ["reading-list", "crypto"], daysAgo: 26, downloads: 34 },
        ],
      },
      {
        name: "Artificial Intelligence",
        code: "CS-412",
        icon: "brain",
        materials: [
          { title: "AI Assignment 02 — Search Algorithms", description: "Implement BFS, DFS and A* on the 8-puzzle, with a short report.", category: "Assignments", instructor: "Dr. Sana Malik", tags: ["search", "a-star"], daysAgo: 1, downloads: 96 },
          { title: "Informed Search — Lecture 05", description: "Heuristics, admissibility, consistency and A* correctness.", category: "Lecture Notes", instructor: "Dr. Sana Malik", tags: ["heuristics", "search"], daysAgo: 9, downloads: 61 },
          { title: "Intro to Machine Learning Deck", description: "Supervised vs unsupervised learning, bias-variance and evaluation metrics.", category: "Presentations", tags: ["ml", "metrics"], daysAgo: 17, downloads: 48 },
          { title: "Stanford CS221 course materials", description: "Open lecture notes for artificial intelligence principles.", category: "External Resources", tags: ["stanford", "notes"], externalUrl: "https://stanford-cs221.github.io/", daysAgo: 24, downloads: 15 },
        ],
      },
      {
        name: "Software Project Management",
        code: "SE-402",
        icon: "chart",
        materials: [
          { title: "Estimation and Planning — Lecture 04", description: "Story points, velocity, COCOMO basics and planning fallacies.", category: "Lecture Notes", tags: ["estimation", "agile"], daysAgo: 6, downloads: 40 },
          { title: "Risk Register Template", description: "Spreadsheet-style template for the project risk assignment.", category: "Assignments", tags: ["risk", "template"], daysAgo: 10, downloads: 37 },
          { title: "Sprint Retrospective Deck", description: "Facilitation formats for retrospectives, with examples.", category: "Presentations", tags: ["scrum", "retro"], status: "draft", daysAgo: 2 },
        ],
      },
      {
        name: "Final Year Project",
        code: "FYP-400",
        icon: "rocket",
        materials: [
          { title: "FYP Proposal Guidelines 2026", description: "Formatting rules, submission dates and the evaluation rubric.", category: "Assignments", instructor: "FYP Committee", tags: ["fyp", "proposal"], daysAgo: 3, downloads: 156 },
          { title: "Literature Review Workshop", description: "How to search, read and summarise papers for the FYP report.", category: "Presentations", tags: ["fyp", "research"], daysAgo: 12, downloads: 58 },
        ],
      },
    ],
  },
];

async function main() {
  const { getPool, query, queryOne } = await import("../src/lib/db");
  const { upsertAdmin } = await import("../src/lib/repo/admins");
  const { getStorageProvider } = await import("../src/lib/storage");
  const { slugify } = await import("../src/lib/utils");

  const email = process.env.ADMIN_EMAIL;
  const password = process.env.ADMIN_PASSWORD;
  if (!email || !password) {
    throw new Error("Set ADMIN_EMAIL and ADMIN_PASSWORD in .env.local before seeding.");
  }
  if (password.length < 8) throw new Error("ADMIN_PASSWORD must be at least 8 characters.");

  const reset = process.argv.includes("--reset");
  if (reset) {
    await query(
      `TRUNCATE download_events, material_tags, tags, materials, subjects, categories, semesters RESTART IDENTITY CASCADE`,
    );
    console.log("• Cleared existing content");
  }

  const admin = await upsertAdmin(email, process.env.ADMIN_NAME || "Class Representative", password);
  console.log(`✓ Admin ready: ${admin?.email}`);

  const categoryIds = new Map<string, string>();
  for (const [i, c] of CATEGORIES.entries()) {
    const row = await queryOne<{ id: string }>(
      `INSERT INTO categories (name, slug, icon, description, sort_order)
       VALUES ($1,$2,$3,$4,$5)
       ON CONFLICT (slug) DO UPDATE SET icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order
       RETURNING id`,
      [c.name, slugify(c.name), c.icon, c.description, i],
    );
    categoryIds.set(c.name, row!.id);
  }
  console.log(`✓ ${CATEGORIES.length} categories`);

  const storage = getStorageProvider();
  let materialCount = 0;

  for (const [si, sem] of DATA.entries()) {
    const semester = await queryOne<{ id: string }>(
      `INSERT INTO semesters (name, slug, short_label, description, sort_order)
       VALUES ($1,$2,$3,$4,$5)
       ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, short_label = EXCLUDED.short_label
       RETURNING id`,
      [sem.name, slugify(sem.name), sem.short, sem.description, si],
    );

    for (const [subi, sub] of sem.subjects.entries()) {
      const subject = await queryOne<{ id: string }>(
        `INSERT INTO subjects (semester_id, name, slug, code, icon, sort_order)
         VALUES ($1,$2,$3,$4,$5,$6)
         ON CONFLICT (semester_id, slug) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon
         RETURNING id`,
        [semester!.id, sub.name, slugify(sub.name), sub.code, sub.icon, subi],
      );

      for (const mat of sub.materials) {
        const slug = slugify(mat.title);
        const exists = await queryOne<{ id: string }>(`SELECT id FROM materials WHERE slug = $1`, [slug]);
        if (exists) continue;

        const status = mat.status ?? "published";
        let storageProvider: string | null = null;
        let storageFileId: string | null = null;
        let fileName: string | null = null;
        let fileType: string | null = null;
        let fileSize: number | null = null;

          if (!mat.externalUrl) {
          const data = placeholderPdf(mat.title, `${sub.name} · ${mat.category} · ${sem.name}`);
          try {
            const stored = await storage.upload({
              data,
              fileName: `${slug}.pdf`,
              mimeType: "application/pdf",
              folderPath: [sem.name, sub.name, mat.category],
            });
            storageProvider = storage.name;
            storageFileId = stored.id;
            fileName = `${slug}.pdf`;
            fileType = "application/pdf";
            fileSize = stored.size;
          } catch (err) {
            console.warn(
              `  ⚠ Skipped "${mat.title}" — ${storage.name} upload failed: ${(err as Error).message}`,
            );
            continue;
          }
        }

        const created = await queryOne<{ id: string }>(
          `INSERT INTO materials
            (title, slug, description, semester_id, subject_id, category_id, instructor, status,
             external_url, storage_provider, storage_file_id, file_name, file_type, file_size,
             download_count, created_at, updated_at, published_at, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,
                   now() - ($16 || ' days')::interval, now() - ($16 || ' days')::interval,
                   CASE WHEN $8 = 'published' THEN now() - ($16 || ' days')::interval ELSE NULL END, $17)
           RETURNING id`,
          [
            mat.title,
            slug,
            mat.description,
            semester!.id,
            subject!.id,
            categoryIds.get(mat.category)!,
            mat.instructor ?? null,
            status,
            mat.externalUrl ?? null,
            storageProvider,
            storageFileId,
            fileName,
            fileType,
            fileSize,
            mat.downloads ?? 0,
            String(mat.daysAgo),
            admin!.id,
          ],
        );

        for (const tag of mat.tags) {
          const tagRow = await queryOne<{ id: string }>(
            `INSERT INTO tags (name, slug) VALUES ($1,$2)
             ON CONFLICT (slug) DO UPDATE SET name = tags.name RETURNING id`,
            [tag, slugify(tag)],
          );
          await query(
            `INSERT INTO material_tags (material_id, tag_id) VALUES ($1,$2) ON CONFLICT DO NOTHING`,
            [created!.id, tagRow!.id],
          );
        }

        // Backfill plausible download history for the analytics charts.
        const downloads = Math.min(mat.downloads ?? 0, 60);
        if (downloads > 0) {
          await query(
            `INSERT INTO download_events (material_id, kind, created_at)
             SELECT $1, 'download', now() - (random() * 29 || ' days')::interval
               FROM generate_series(1, $2)`,
            [created!.id, downloads],
          );
        }
        materialCount++;
      }
    }
  }

  console.log(`✓ ${materialCount} demo materials (storage provider: ${storage.name})`);
  console.log("\nDemo data is fictional. No copyrighted textbooks are included;");
  console.log("materials without rights to redistribute link to an authorised source instead.\n");
  await getPool().end();
}

main().catch((err) => {
  console.error("✕ Seed failed:", err);
  process.exit(1);
});
